name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: 45.79.125.127
          username: root
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd /var/www/html/crud-cicd-practice

            git pull origin main

            composer install --no-dev --optimize-autoloader

            php artisan migrate --force

            php artisan optimize:clear

            php artisan config:cache
            php artisan route:cache
            php artisan view:cache